<?php get_header();
?>

<div class="parallax full-width-bg lr_widget">
  <div class="container">
    <div class="main-title">
      <div class="column dt-sc-three-fifth first">
        <h1>Terms of Use</h1>
      </div>
      <!--		<div class="column dt-sc-two-fifth first ">
           <a class="dt-sc-button large f_right" href="/startupsignup/">Register <span class="fa fa-angle-right"></span></a>
		                           <a class="dt-sc-button large mr10 f_right" href="/login/">Login <span class="fa fa-angle-right"></span></a> 

		</div>-->
    </div>
  </div>
</div>
<!-- Container starts-->
<div class="full-width-section grey1">
  <div class="dt-sc-margin30"></div>
  <div class="container">
    <div class="hr-title dt-sc-hr-invisible-small">
	<strong>This document is an electronic record in terms of the Information Technology Act, 2000 and the rules framed thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.<br><br>
This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the http://www.ivycamp.in website.</strong><br><br>

IVAPL.‏ is a company incorporated under the laws of India with its registered office at  G2 Spectra Building, Hiranandani Gardens, Powai, Mumbai 400076 (hereinafter referred to as "<strong>We</strong>", "<strong>Us</strong>", "<strong>IVAPL</strong>" or "<strong>Our</strong>" which expression shall mean and include its affiliates, successors and permitted assigns). Your ("<strong>You</strong>" or "<strong>Your</strong>") use of the Website (defined below) is subject to the notices, terms and conditions set forth in these Terms of Use. The domain name "<strong>www.ivycamp.in</strong>" (hereinafter referred to as the "Website") is owned by IVAPL. Your use of the Website is governed by the following terms and conditions ("Terms of Use") as applicable to the Website including the applicable policies which are incorporated herein by way of reference. You acknowledge and agree that You shall be subject to the policies that are applicable to the Website and by mere use of the Website, You shall be contracting with IVAPL and these terms and conditions including the policies constitute Your binding obligations, with IVAPL.<br><br>

By mere use of the Website, You agree to be subject to the applicable rules, guidelines, policies, terms, and conditions and the same shall be deemed to be incorporated into this Terms of Use and be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.<br><br>

<strong>ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE INDICATES YOUR ACCEPTANCE OF ALL THE TERMS AND CONDITIONS IN THESE TERMS OF USE. PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE PROCEEDING. YOU DECLARE YOUR WILLINGNESS TO ABIDE AND BE BOUND BY THESE TERMS OF USE THROUGH YOUR USE OF THE WEBSITE. IF YOU DO NOT AGREE WITH THE TERMS OF USE, PLEASE DO NOT USE THIS WEBSITE. These Terms of Use will be effective immediately upon Your acceptance of Our terms and conditions, Your use of Our Website being indicative of such acceptance. These Terms of Use shall be enforceable against You in a the same manner as any other written agreement.</strong>

    </div>
    <!-- **column - Starts** -->
    <div class="hr-title dt-sc-hr-invisible-small">
	  <h2>What we do</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     We provide a platform through which the new innovators, new and growing businesses and registered users can interact with each other for the purpose of evaluating a potential business relationship and through such platform, facilitate the validation of the business ideas provided by the businesses as well as effective and secure communication between such businesses and other users. The registered users will be able to view summary information of other registered users including (but not limited to) mentor/investor/corporate/partner/incubator profiles, innovator/startup summary information  for the purpose of identifying and selecting the right partner to engage with. We may also provide certain offline services which may include but not be limited to conducting seminars, workshops and providing an opportunity to the users of the Website to interact with other users of the Website offline.
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Emails, Newsletters and Notifications</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
      If You wish to subscribe to Our newsletter(s) or receive notifications or e-mails from Us, We will use Your name and latest e-mail address provided by You in this regard. However, You may choose to stop receiving Our newsletters by following the instructions to unsubscribe as included in these e-mails or You can contact Us at ivycamp@ivycapventures.com.
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Intellectual Property</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     This Website is operated by and is the sole property of IVAPL. Any and all material on this Website, including images, illustrations, audio and video clips are protected by copyrights, trademarks, and other intellectual property rights that are owned by Us or by other parties that have licensed such material to Us, or such parties having ownership of content uploaded on the Website. You agree that any and all material displayed on the Website is solely for Your personal use and You shall not, whether directly or indirectly, copy, reproduce, republish, post, upload, transmit or distribute such material in any manner and through any media including by way of e-mail or other electronic means and You shall not assist any other person in doing so. Modification of the said materials or use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal use is a violation of the said copyrights, trademarks and other intellectual proprietary rights, and is expressly prohibited. 
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Prohibited Uses</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     The Website may be used only for lawful purposes. IVAPL  specifically prohibits any use of the Website for and 
	<ol type="a" class="dt-sc-fancy-list arrow lcolor">
        <li>Modifying, publishing, transmitting, distributing, displaying, performing, participating in the transfer or sale of, create derivative works on, or in any way exploiting, any of the copyrighted material contained on the Website, in whole or in part, without Our prior written consent; or</li>
		<li>Subleasing, leasing, selling, assigning, transferring, distributing, renting, permitting concurrent use of, or granting other rights in the content and any material and documentation provided on the Website to any third party; or</li>
		<li>Providing use of the content in a computer service business, network, time sharing, interactive cable television, multiple CPU or multiple or concurrent user arrangement to users who are not individually licensed by IVAPL or otherwise exploiting any portion of, the use of or access to the content or the materials or documentation provided on the Website in contravention of these Terms of Use.</li>
	</ol>

    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Modifications</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     We reserve the right at any time and from time to time, in Our sole discretion, to modify the content on the Website or any part thereof, including the transmission of any related materials or documentation, with or without providing prior notice to You. We further reserve the right at any time and from time to time, at Our sole discretion, to alter, modify or terminate any content or features contained on the Website without providing to You prior notice of such alteration, modification or termination. You agree that IVAPL shall not be liable to You or to any third party claiming through You, for any modification of the content or features provided on the Website.
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>System Limitations and Failures</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     We use internally developed systems for providing You access to and facilitating Your use of the Website. These systems may encounter technical or other limitations, and computer and communications hardware systems might experience interruptions. Further, We continually enhance and improve these systems in order to accommodate the level of use of the Website. We may also add additional features and functionality to Website that might result in the need to develop or license additional technologies. Increased utilization of the Website or providing new features or functionality may cause unanticipated system disruptions, slower response times, degradation in levels of customer service, and delays in reporting accurate financial information. You agree that We shall not be liable to You or to any third party claiming through You, for any such failures contemplated herein. 
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Privacy and Confidentiality</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     Your use of the Website is governed by Our Privacy Policy, which can be located at http://www.ivycamp.in/Privacy.<br>
Please read Our Privacy Policy to understand Our information collection and usage practices. You may obtain certain confidential information, including without limitation, technical, contractual, product, pricing and other valuable information that should reasonably be understood as confidential ("<strong>Confidential Information</strong>"). You acknowledge and agree to hold all Confidential Information in strict confidence. Title and all interests to all Confidential Information shall be vested in Us. Your obligations regarding Confidential Information will survive the termination of these Terms of Use in accordance with Clause 11 below. Upon such termination, You must stop forthwith using any Confidential Information to which You may have been exposed in due course of Your use of the Website. <br>
You agree that Your obligations under this Clause 7 are necessary and reasonable in order to protect Our business and expressly agree that monetary damages would be inadequate to compensate for any breach of any covenant or agreement set forth herein. Accordingly, You agree and acknowledge that any such violation or threatened violation will cause irreparable harm and injury to IVAPL and that, in addition to any other remedies that may be available, in law, equity or otherwise, IVAPL shall be entitled to obtain injunctive relief against the threatened breach of the terms of this Clause or the continuation of any such breach.

    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Links to / from other Websites</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     The Website may contain link/s to various other websites. These links are provided solely for Your convenience and benefit. Wherever such link/s lead to websites which are not owned by or belong to IVAPL, We shall not be responsible for the content, products and services provided on such linked sites. We do not warrant or make any representations regarding the correctness or accuracy of the content on such websites. If You decide to access such linked websites, You do so at Your own risk. We do not in any way endorse the linked websites.<br>
Similarly, this Website can be made accessible through a link created by other websites. Access to this Website through such link/s shall not mean or be deemed to mean that the objectives, aims, purposes, ideas, concepts of such other websites or their aim or purpose in establishing such link/s to this Website are necessarily the same or similar to the idea, concept, aim or purpose of Our Website or that such links have been authorized by Us. We are not responsible for any representation/s of such other websites while affording such link and no liability can arise upon IVAPL consequent to such representation, its correctness or accuracy. In the event that any link/s afforded by any other website/s derogatory in nature to the objectives, aims, purposes, ideas and concepts of this Website, is utilized to visit this Website and such event is brought to the notice or is within the knowledge of IVAPL, civil or criminal remedies as may be appropriate shall be invoked.

    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Security</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
     You are prohibited from violating or attempting to violate the security of the Website, including, without limitation: (a) accessing data not intended for You or logging into an account which You are not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; or attempting to interfere with service to any user, host, or network.<br> 
You shall not misuse this Website by knowingly introducing viruses, trojans, worms, logic bombs or other materials that are malicious or technologically harmful (together "Viruses"). You must not attempt to gain unauthorized access to our Website, the server on which the Website is stored or any server, computer or database connected to this Website. You must not attack this Website via a denial-of-service attack.<br>
By breaching the provisions of this Clause 9, you may be liable to be prosecuted under the Information Technology Act, 2000 and any other applicable law. We will report any such breach to the relevant law enforcement authorities and we will co-operate with such authorities by disclosing Your identity to them. In the event of such a breach, Your rights to use this Website will cease immediately.<br>
We will not be liable for any loss or damage caused by a denial-of-service attack or Viruses that may infect your computer equipment, computer programs, data or other proprietary material due to Your use of this Website or to your downloading of any material posted on it, or on any website linked to it. <br>
You agree to immediately report to Us all incidents involving suspected or actual unauthorized access, disclosure, alteration, loss, damage, or destruction of data.

    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Monitoring </h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
    All electronic communications and content presented and / or passed to Us, including that presented and / or passed from remote access connections, may be monitored, examined, saved, read, transcribed, stored, or retransmitted in the course of daily operations by any duly authorized employee or agent of IVAPL in the exercise of their duties, or by law enforcement authorities who may be assisting IVAPL  in investigating possible contravention / non-compliance with applicable law. Electronic communications and content may be examined by automated means. Further, IVAPL has the right to reject, at its sole discretion, from the Website any electronic communications or content deemed not to be in compliance with the corporate policies and procedures of IVAPL.
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Termination</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
   In the event it is determined by Us that You have violated any of these Terms of Use, We shall have the right, at Our sole discretion, to suspend Your use of and prohibit access to any or all features / parts of the Website forthwith. Any such suspension or termination of access to Website may be effected by Us without providing You with a prior written notice in this regard. Upon such termination of access to the Website, these Terms of Use, as applicable to You, will be deemed to have been terminated.<br>
You acknowledge and agree that, upon termination, You shall immediately destroy any copies made of any portion of the content contained on the Website. You acknowledge and agree that IVAPL shall not be liable to You or any third party claiming through You, for any suspension or termination of access to Website.

    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Disclaimer of Warranties and Limitation of Liability</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
   IVAPL does not endorse or act on behalf of any third party. In the event You engage the services of / interact with any third party, through the Website, IVAPL will not be liable to You for any act or omission by such third party in relation thereto.<br>
We hereby expressly disclaim all warranties and representations of any kind with respect to any and all content and features available on the Website, including but not limited to (a) warranties as to merchantability or use for a particular purpose whether or not IVAPL knows or has reason to know or has been advised of any such purpose or (b) warranties as to any results to be obtained from any use of the IVAPL content or information derived from use of the Website. <br>
IVAPL shall have no liability for any losses, direct or indirect, in contract, tort, or otherwise, incurred in connection with the IVAPL content on the Website, including but not limited to loss of revenue or profit or any other commercial or economic loss or for any decision made or action taken by any third party in reliance upon the IVAPL content.<br>
You agree to indemnify and hold IVAPL harmless from any claim or demand, including reasonable attorney's fees and expenses, made by any third party due to or arising out of Your use of the Website, the violation of the terms of this Agreement by You, or Your infringement of any intellectual property or other right of any person or entity, or as a result of any threatening, libelous, obscene, harassing or offensive material posted / transmitted by You on the Website .<br>
Your obligations under this Clause 12 shall survive the termination of these Terms of Use in accordance with Clause 11 above.


    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Foreign Jurisdictions</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
   IVAPL makes no representation that the content contained on the Website is appropriate or to be used or accessed outside of India. If You use or access the Website from outside India, You do so at Your own risk and are responsible for compliance with the laws of such jurisdiction. 
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Governing Law and Dispute Resolution</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
   These Terms of Use shall be governed by and construed in accordance with the laws of India and subject to the provisions of arbitration set out herein, the courts in India shall have exclusive jurisdiction in relation to any disputes arising out of or in connection with these Terms of Use. <br>
If any dispute arises between IVAPL and You during the subsistence of these Terms of Use or thereafter, in connection with or arising out of the validity, interpretation, implementation or alleged breach of any provision of these Terms of Use or regarding a question, such dispute shall be referred to and finally resolved by arbitration under the laws of India <br>
There shall be one (1) arbitrator and the venue of arbitration shall be Mumbai, India<br>
The language of the arbitration proceedings and of all written decisions and correspondence relating to the arbitration shall be English.

    </div>
	
	
		
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>Severability</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
   If any term, provision, covenant or restriction of these Terms of Use is held by a court of competent jurisdiction to be invalid, void or unenforceable, the remainder of the terms, provisions, covenants and restrictions of these Terms of Use shall remain in full force and effect and shall in no way be affected, impaired or invalidated.
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>No Waiver</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
  The rights and remedies available under this Terms of Use may be exercised as often as necessary and are cumulative and not exclusive of rights or remedies provided by law. It may be waived only in writing. Delay in exercising or non-exercise of any such right or remedy does not constitute a waiver of that right or remedy, or any other right or remedy.
    </div>
	
	
	<div class="hr-title dt-sc-hr-invisible-small">
      <br>
	  <h2>General</h2>
      <div class="title-sep"> </div>
    </div>
    <div class="column dt-sc-five-fifth first">
   These Terms of Use comprise the full and complete agreement between You and IVAPL with respect to the use of the Website and supersedes and cancels all prior communications, understandings and agreements between You and IVAPL, whether written or oral, expressed or implied with respect thereto. 
    </div>
    
    
  </div>
  <!-- **container - Ends** -->
  <div class="dt-sc-margin50"></div>
</div>
<div class="dt-sc-margin65"></div>
<!-- **container - Ends** -->
<?php get_footer(); ?>
